language: objective-c
osx_image: xcode10
# xcode_sdk: iphonesimulator11
# xcode_project: Loop.xcodeproj
# xcode_scheme: Loop
before_script:
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -target Cartfile
script:
    # Build the app target
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -scheme Loop build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
    # Run the test target
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -scheme LoopTests -destination 'name=iPhone SE' test | xcpretty
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -scheme DoseMathTests -destination 'name=iPhone SE' test | xcpretty
